framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false
  handle_all_throwables: true

  serializer:
    enabled: true


  cache:
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_URL)%'

  messenger:
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
    routing:
      'App\Message\PublishNotificationMessage': async

when@dev:
  framework:
    profiler: { only_exceptions: false }
