framework:
  workflows:
    leave_request:
      type: 'state_machine'
      supports:
        - App\Entity\LeaveRequest
      marking_store:
        type: 'method'
        property: 'status'
      initial_marking: 'DRAFT'
      places:
        - DRAFT
        - SUBMITTED
        - MANAGER_APPROVED
        - HR_APPROVED
        - REJECTED
        - CANCELLED
      transitions:
        submit:
          from: DRAFT
          to: SUBMITTED
        cancel_from_draft:
          from: DRAFT
          to: CANCELLED
        cancel_from_submitted:
          from: SUBMITTED
          to: CANCELLED
        manager_approve:
          from: SUBMITTED
          to: MANAGER_APPROVED
        hr_approve:
          from: MANAGER_APPROVED
          to: HR_APPROVED
        reject_from_submitted:
          from: SUBMITTED
          to: REJECTED
        reject_from_manager:
          from: MANAGER_APPROVED
          to: REJECTED
